# name: Linting

# on: push

# jobs:
  # rust_lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Install dependencies (ubuntu only)
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libasound2-dev
  #     - run: rustup component add clippy
  #     - name: Rust Clippy
  #       run: cd ./engine/ && cargo clippy --all-targets --all-features -- -D warnings

  # typescript_lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: pnpm/action-setup@v2.0.1
  #       with:
  #         version: 6.20.3
  #     - name: Use Node.js 16
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         cache: 'pnpm'
  #     - name: Install node modules
  #       run: pnpm install
  #     - name: Lint typescript
  #       run: pnpm lint
